// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbHHLm2Blvt-iVLWjHxdRqt0uOEHC4Ofo',
    appId: '1:601254525660:web:105792e293ece71c085219',
    messagingSenderId: '601254525660',
    projectId: 'maps-3ca38',
    authDomain: 'maps-3ca38.firebaseapp.com',
    storageBucket: 'maps-3ca38.appspot.com',
    measurementId: 'G-PLZ1CL3WDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8mHMGnsXqPFfdA8Ex83rnx_LsUUC3mFc',
    appId: '1:601254525660:android:4810e809bd7b0f82085219',
    messagingSenderId: '601254525660',
    projectId: 'maps-3ca38',
    storageBucket: 'maps-3ca38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqwotRL2HXpaFmSwzGwf789xLv_X8C3M8',
    appId: '1:601254525660:ios:5fa3624e690fcdd7085219',
    messagingSenderId: '601254525660',
    projectId: 'maps-3ca38',
    storageBucket: 'maps-3ca38.appspot.com',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqwotRL2HXpaFmSwzGwf789xLv_X8C3M8',
    appId: '1:601254525660:ios:5fa3624e690fcdd7085219',
    messagingSenderId: '601254525660',
    projectId: 'maps-3ca38',
    storageBucket: 'maps-3ca38.appspot.com',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbHHLm2Blvt-iVLWjHxdRqt0uOEHC4Ofo',
    appId: '1:601254525660:web:342886991201a1be085219',
    messagingSenderId: '601254525660',
    projectId: 'maps-3ca38',
    authDomain: 'maps-3ca38.firebaseapp.com',
    storageBucket: 'maps-3ca38.appspot.com',
    measurementId: 'G-53C7BXVNER',
  );
}
